### ISSUE TITLE
Doesn't work with all packages

### ISSUE THREAD

**Issue by GitBoffen** [MehediH/winstall#10]
The scripts generated will not work with some specific packages, like Git and GIMP since there are multiple packages with the same name (capitalized and non capitalized), for it to work you need to add -e / --exact to be able to install the package.

**Comment by MehediH** [comment]
The script already specifies the `--id` which should target the app package directly, regardless of if it has different variations. Have you tried this and does it not work?

**Comment by GitBoffen** [comment]
It does not work since there are two packages with the same name, but one is not capitalized and one is capitalized so it does not know what it should install if you don't use --exact.

**Comment by MehediH** [comment]
So if you try to install GitLFS (https://github.com/microsoft/winget-pkgs/blob/master/manifests/Git/GitLFS/2.11.0.yaml) does it install Git (https://github.com/microsoft/winget-pkgs/blob/master/manifests/Git/Git/2.24.1.2.yaml) instead of GitLFS?

**Comment by GitBoffen** [comment]
![image](https://user-images.githubusercontent.com/60466684/82738159-066fb380-9d36-11ea-9b2d-677779443074.png)

**Comment by MehediH** [comment]
And could you please show me the output for when you run `winget install --id=Git.Git --exact` and `winget install --id=Git.GitLFS --exact`?

Sorry I don't have access to a Windows machine atm.

**Comment by GitBoffen** [comment]
![image](https://user-images.githubusercontent.com/60466684/82738223-5b132e80-9d36-11ea-8798-dfdf4552c927.png)

**Comment by MehediH** [comment]
Thanks, I just pushed a new patch, should be fixed!

**Comment by GitBoffen** [comment]
A better example would be GIMP since there are two packages (gimp.gimp and GIMP.GIMP)
![image](https://user-images.githubusercontent.com/60466684/82738264-b04f4000-9d36-11ea-8431-1dc0cd92f6de.png)
