### ISSUE TITLE
Linstall?

### ISSUE THREAD

**Issue by ehawman-rosenberg** [MehediH/winstall#105]
I've been searching for a Winstall counterpart for Linux and have come up short.

So far the only thing I've found that remotely does the same thing is browsing [a distro's packages](https://packages.ubuntu.com/) and collecting up package names. That lacks the cloud functionality and easy editing/sorting that Winstall offers.

Could the fundamentals of Winstall be copied for Linux?

**Comment by MehediH** [comment]
winstall is basically just a scraper with a nice UI, so anyone can go and make a service that scrapes the Linux distro packages and render it in a nice looking UI w/ all the sorting features. Unfortunately I do not have the bandwidth to work on a new project like this, but feel free to look into it
