### ISSUE TITLE
Sorry! We could not load this pack. Recieved error: [object Object]

### ISSUE THREAD

**Issue by seniorweasel** [MehediH/winstall#112]
Hello! I got an error from Winstall.app like in this screenshot. I don't know anyone is living that issue or not, just wanted to report it on there
![Ekran Görüntüsü (3)](https://user-images.githubusercontent.com/43583053/169361199-df3992fa-2d27-4198-a706-ed5cccabf7e9.png)

**Comment by DeusMaximus** [comment]
Issue still occurring on every app I've tried. While you can still search for apps, and generate scripts, you can't look at an individual app's page anymore.

**Comment by MehediH** [comment]
Sorry for the late response here, folks. I was on holiday - fixed now.
