### ISSUE TITLE
invalid json response body

### ISSUE THREAD

**Issue by 0ud** [MehediH/winstall#113]
When I open the packs page or go into my profile I get the error:

invalid json response body at https://api.winstall.app/packs reason: Unexpected token < in JSON at position 0

**Comment by thorrrr** [comment]
I also see this issue unable to see any packs

**Comment by fernandoccandidoo** [comment]
Did the dev abandon the project?

**Comment by MehediH** [comment]
Sorry for the late response here, folks. I was on holiday - fixed now.
