### ISSUE TITLE
[QUESTION] Open API for the icon engine?

### ISSUE THREAD

**Issue by marticliment** [MehediH/winstall#129]
Hi,

I found that your project dynanimcally loads icons for Winget packages, and I was wondering if you used any api, or if you have your own api. If you have your own, is it open?

It is because i'm developping a dersktop app to manager winget (and scoop) apps, and i'd like to get icons involved.

Thank you!

**Comment by Spacellary** [comment]
I have a lot of interest in this too. Bump, bump!

**Comment by Satanarious** [comment]
Any update on this?

**Comment by MehediH** [comment]
the winstall API doesn't do anything fancy to for the icon engine - I simply use this npm library https://www.npmjs.com/package/get-website-favicon to get an app's website icon, then find the best resolution favicon file, and use that as the icon for the app. 

this is then downloaded and saved in the winstall backend

**Comment by Spacellary** [comment]
Thanks for taking the time to reply here, Mehdi!

**Comment by marticliment** [comment]
Thank you! This will definitely help me implement the icon engine!
