### ISSUE TITLE
Erros to acess my profile "Unexpected token 'S', "Something "... is not valid JSON"

### ISSUE THREAD

**Issue by rafaelsouzams** [MehediH/winstall#148]
I have this error when I access my profile to see my packs.
It's been about 3 days since I noticed this, and it continues to this day.

![image](https://github.com/MehediH/winstall/assets/25182245/ba1147f6-7df1-4aa0-aceb-0db1140c0b93)

**Comment by MehediH** [comment]
should be fixed now
