### ISSUE TITLE
error loading pack

### ISSUE THREAD

**Issue by mpusch88** [MehediH/winstall#151]
![image](https://github.com/MehediH/winstall/assets/11446016/c340c060-7b9e-44de-a587-c79f4d549dfb)

packs/xzlu959dM

**Comment by mpusch88** [comment]
Note - I can still see this pack's contents by clicking edit

**Comment by mayberts** [comment]
I think this is a bigger issue, I'm unable to log in or view any apps

Login error
![image](https://github.com/MehediH/winstall/assets/27490448/019956bb-f60d-484e-ab68-2b6b0e1b0e33)

App error
![image](https://github.com/MehediH/winstall/assets/27490448/9ff33e76-f47b-4738-ac60-5566a0c140a6)
