### ISSUE TITLE
Link of 'apps available' on readme.md doesn't work

### ISSUE THREAD

**Issue by ErickRock** [MehediH/winstall#2]
![image](https://user-images.githubusercontent.com/15223763/82684701-6b89b300-9c29-11ea-991d-22ea998534f1.png)

![image](https://user-images.githubusercontent.com/15223763/82684902-b86d8980-9c29-11ea-94c1-465bc060e2a8.png)

**Comment by MehediH** [comment]
Thanks, fixed now.
