### ISSUE TITLE
ONLYOFFICE not showing up in search

### ISSUE THREAD

**Issue by Weasy666** [MehediH/winstall#21]
If you search for `onlyoffice` it does not appear as a search result, despite being in the repository
https://github.com/microsoft/winget-pkgs/tree/master/manifests/ONLYOFFICE/DesktopEditors

**Comment by MehediH** [comment]
This is a problem with encoding the yaml file, where some files have weird characters that can't be decoded properly -- please see: https://twitter.com/DenelonMs/status/1263875852879593472

If you try to view the file on the commit, for example, it doesn't show the file preview: https://github.com/microsoft/winget-pkgs/commit/7352b127733f60617cdd8af706b1c4fba0929be0#diff-bb134b19331c49729dfe16acdd21be2b

If you fix the issue and re-add it to the repository, it will get picked up by the API.

**Comment by Weasy666** [comment]
Ah...ok...i was wondering why github didn't show the file content. Thx for the info.
Will try to fix it in the repo.

So i guess we can close this issues, except you want it to be open for others to see.
