### ISSUE TITLE
How to provide icons for an app?

### ISSUE THREAD

**Issue by tranzystorek-io** [MehediH/winstall#23]
With the addition of icons comes the question: where does the winstall api get app icons from? The winget manifest does not seem to support icon urls.

**Comment by MehediH** [comment]
The API makes the best effort to obtain and process the favicon of the homepage url provided in the manifests. If your app’s homepage url is a GitHub link, an icon won’t be set because that would just be the GitHub icon.

**Comment by tranzystorek-io** [comment]
Thanks, this answers my question 😄
