### ISSUE TITLE
App Version Dropdown Unreadable in Dark Mode

### ISSUE THREAD

**Issue by pranavb** [MehediH/winstall#36]
## Issue
When using dark mode, the drop down with all the available versions for an app is displayed with dark text on a dark background making it unreadable.

## Screenshot
![Screen Shot 2020-10-02 at 9 10 12 AM](https://user-images.githubusercontent.com/4624129/94945250-4470a700-048f-11eb-8963-3fb9f34b38a5.png)

_Captured on Microsoft Edge (`85.0.564.63`)_

**Comment by MehediH** [comment]
Thanks! Should be fixed shortly.
