### ISSUE TITLE
Edge App uses the Description for the App Name

### ISSUE THREAD

**Issue by MLisDreaming** [MehediH/winstall#44]
When turning the webpage into a Edge Webapp, it uses the description.
![image](https://user-images.githubusercontent.com/43427333/99757830-d7a08300-2ab5-11eb-9326-18d30239324a.png)
![image](https://user-images.githubusercontent.com/43427333/99757796-bf306880-2ab5-11eb-8076-d81dcbbf53f3.png)
![image](https://user-images.githubusercontent.com/43427333/99757726-97410500-2ab5-11eb-974a-472b74aa0c09.png)
![image](https://user-images.githubusercontent.com/43427333/99757814-cc4d5780-2ab5-11eb-8c46-6db7ef765626.png)

**Comment by MehediH** [comment]
Fixed!
