### ISSUE TITLE
Chocolatey support

### ISSUE THREAD

**Issue by Daniel-Vinicius** [MehediH/winstall#49]
Hello I'm Daniel and I would like to place an order, I found the winstall sensational! But I can't install the winget, and I like chocolatey better, you could add a way to install via chocolatey on the Get the pack script screen, thanks!

---

Some useful things

https://stackoverflow.com/questions/45602103/get-list-of-chocolatey-packages-using-api

choco list --limit-output

---
**Example**

![Sem título](https://user-images.githubusercontent.com/66279500/110390072-2f063700-8044-11eb-8045-72ff8e9aac4a.png)

---

My mistake when installing the winget is this:

Application installation failed with the error message: error 0x80070005: Failed to open the package from location a.appxbundle. (0x80070005)

**Comment by MehediH** [comment]
winstall is only meant for winget, not choco. You should open an issue in the winget repo about the installation issue.

**Comment by Daniel-Vinicius** [comment]
My Issue aims to make a suggestion
