### ISSUE TITLE
Add option to pass some Parameters

### ISSUE THREAD

**Issue by GamerClassN7** [MehediH/winstall#50]
HI,
would be possible to add for example this 3 are really crucial for my work in Company :)

  -o,--log          Log location (if supported)
  -l,--location     Location to install to (if supported)
  --force           Override the installer hash check

**Comment by MehediH** [comment]
Added now :)

**Comment by GamerClassN7** [comment]
> Added now :)

Hi how can i use them ? :) i dont see them anyvhere in ui :(

**Comment by GamerClassN7** [comment]
Advance options Nice!
