### ISSUE TITLE
unable / broken reinstall or update installation apps?

### ISSUE THREAD

**Issue by Vondelphia** [MehediH/winstall#52]
can winstall detect that a program is already installed, OR WAS JUST Installed and just skip over it?? there seems to be a hiccup when "reinstalling" brave / winrar for example. it halts progress and does not over-install over those. here is the winstall one i generated and used. 

[winstall (2).zip](https://github.com/MehediH/winstall/files/6218294/winstall.2.zip)

i generated one package with 8 apps. forgot an app, and re-generated another winstall but when i tried to run that, i was getting errors. does this winstall software support "over installing" already installed apps?

![image](https://user-images.githubusercontent.com/16372882/112771728-27ea9d00-8fe2-11eb-98c8-421908c9070c.png)

and also `Installer failed with exit code: 1223` too.

**Comment by MehediH** [comment]
This is a winget issue.
