### ISSUE TITLE
Bug: two webview2 evergreens

### ISSUE THREAD

**Issue by oxygen-dioxide** [MehediH/winstall#58]
![image](https://user-images.githubusercontent.com/54425948/117466284-1f906500-af85-11eb-88e9-5a09b6cd2491.png)

**Comment by Teraskull** [comment]
Duplicates should be reported to https://github.com/microsoft/winget-pkgs. Otherwise, this issue is already fixed and can be closed.

**Comment by oxygen-dioxide** [comment]
No, in winget-pkgs repo there is only one webview2-evergreen. However,winstall shows 2 webview2-evergreens.
![image](https://user-images.githubusercontent.com/54425948/120258117-0ba9fb80-c2c4-11eb-9e34-23901df5d167.png)

**Comment by Teraskull** [comment]
It doesn't show two for me now.
