### ISSUE TITLE
App-Page Sorting Order by Name is wrong

### ISSUE THREAD

**Issue by AlexBoXY** [MehediH/winstall#66]
the Sorting Order by Name Descending/Ascending on the App-Page is mixed up.
Ascending is supposed to sort from A - Z
Descending should sort from Z - A
![image](https://user-images.githubusercontent.com/78037878/119992397-cab39d80-bfca-11eb-81d7-e46d49f4c761.png)
![image](https://user-images.githubusercontent.com/78037878/119992563-f8004b80-bfca-11eb-8797-6906231f6d58.png)

**Comment by MehediH** [comment]
Fixed, thanks!
