### ISSUE TITLE
View Packs page did not reflect edits made after pressing Update Pack in Edit Packs Page.

### ISSUE THREAD

**Issue by jerrywoo96** [MehediH/winstall#71]
To Reproduce:
1) Create a New Pack, add title, description, and 5 packs.
2) Save => Shows correctly in the view packs page.
3) Select Edit Pack that was just created from the steps above.
4) Make changes to title, desc and add more packs
5) Press Update Packs
6) View Packs page did not display updated changes.

**Comment by jerrywoo96** [comment]
Update:
View Packs page did not immediately reflect changes.
Pressing Edit Pack shows the correctly reflected changes.
Pressing update pack again without any new changes => goes back to view pack but still does not show the most updated changes.

**Comment by MehediH** [comment]
This is by design, due to the limited resources I have for winstall. If this changes in the future, the limitation will be taken out. 

![image](https://user-images.githubusercontent.com/10274434/121877788-eaed9700-cd02-11eb-8121-455fc2dc10aa.png)
